apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin
spec:
  secretName: pgadmin
  dnsNames:
    - "pgadmin.st.dta.hasankarimi.ir"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
