apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: basic-scheduler
spec:
  secretName: basic-scheduler
  dnsNames:
    - "bs.st.dta.hasankarimi.ir"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
