name: master
on: push

jobs:
  stage-deploy:
    continue-on-error: true
    strategy:
      matrix:
        apps:
          - postgres
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONF }}
          KUBE_CONTEXT: outi
        with:
          args: apply -k ${{ matrix.apps }}/overlays/stage
